from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 620)
        MainWindow.setMinimumSize(QtCore.QSize(741, 620))
        MainWindow.setMaximumSize(QtCore.QSize(741, 620))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 751, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 81, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_7.setGeometry(QtCore.QRect(100, 260, 113, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 67, 17))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(80, 430, 86, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(60, 470, 86, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 60, 121, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 300, 67, 21))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 220, 67, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 220, 121, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(50, 20, 201, 17))
        self.label_13.setObjectName("label_13")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(20, 430, 67, 17))
        self.label_10.setObjectName("label_10")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 140, 121, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 100, 141, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 60, 51, 20))
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 350, 67, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_8.setGeometry(QtCore.QRect(120, 390, 211, 25))
        self.lineEdit_8.setMaxLength(16)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 97, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(20, 470, 67, 17))
        self.label_11.setObjectName("label_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(60, 510, 113, 25))
        self.lineEdit_9.setMaxLength(4)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 61, 21))
        self.label_4.setObjectName("label_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setGeometry(QtCore.QRect(90, 300, 86, 25))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 390, 101, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 180, 141, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 550, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 510, 67, 17))
        self.label_12.setObjectName("label_12")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setGeometry(QtCore.QRect(70, 350, 86, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(343, 10, 20, 571))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(500, 20, 71, 17))
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(360, 70, 151, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(550, 70, 67, 17))
        self.label_18.setObjectName("label_18")
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_8.setGeometry(QtCore.QRect(550, 100, 112, 23))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_9.setGeometry(QtCore.QRect(550, 130, 112, 23))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_10.setGeometry(QtCore.QRect(550, 160, 112, 23))
        self.radioButton_10.setObjectName("radioButton_10")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_12.setGeometry(QtCore.QRect(360, 90, 151, 25))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(490, 190, 89, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit.setGeometry(QtCore.QRect(380, 450, 321, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(480, 490, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.webView = QtWebEngineWidgets.QWebEngineView(self.tab_2)
        self.webView.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 450, 91, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar.setGeometry(QtCore.QRect(110, 450, 121, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 450, 111, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.radioButton = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton.setGeometry(QtCore.QRect(270, 490, 112, 23))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_2.setGeometry(QtCore.QRect(270, 520, 112, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 490, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.webView_2 = QtWebEngineWidgets.QWebEngineView(self.tab_2)
        self.webView_2.setGeometry(QtCore.QRect(0, 480, 251, 103))
        self.webView_2.setMinimumSize(QtCore.QSize(0, 103))
        self.webView_2.setMaximumSize(QtCore.QSize(16777215, 103))
        self.webView_2.setUrl(QtCore.QUrl("about:blank"))
        self.webView_2.setObjectName("webView_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Supreme Bot"))
        self.label_6.setText(_translate("MainWindow", "Post Code:"))
        self.label_3.setText(_translate("MainWindow", "Tel:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "01"))
        self.comboBox.setItemText(1, _translate("MainWindow", "02"))
        self.comboBox.setItemText(2, _translate("MainWindow", "03"))
        self.comboBox.setItemText(3, _translate("MainWindow", "04"))
        self.comboBox.setItemText(4, _translate("MainWindow", "05"))
        self.comboBox.setItemText(5, _translate("MainWindow", "06"))
        self.comboBox.setItemText(6, _translate("MainWindow", "07"))
        self.comboBox.setItemText(7, _translate("MainWindow", "08"))
        self.comboBox.setItemText(8, _translate("MainWindow", "09"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "2019"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2020"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "2021"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "2022"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "2023"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "2024"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "2025"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "2026"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "2027"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "2028"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "2029"))
        self.label_7.setText(_translate("MainWindow", "Country:"))
        self.label_5.setText(_translate("MainWindow", "City:"))
        self.label_13.setText(_translate("MainWindow", "SHIPPING INFORMATION:"))
        self.label_10.setText(_translate("MainWindow", "Month:"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_8.setText(_translate("MainWindow", "Card:"))
        self.label_2.setText(_translate("MainWindow", "Email:"))
        self.label_11.setText(_translate("MainWindow", "Year:"))
        self.label_4.setText(_translate("MainWindow", "Address:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "UK"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "AUSTRIA"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "BELARUS"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "BELGIUM"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "BULGARIA"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "CROATIA"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "CZECH REPUBLIC"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "DENMARK"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "ESTONIA"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "FINLAND"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "FRANCE"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "GERMANY"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "GREECE"))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "HUNGARY"))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "ICELAND"))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "IRELAND"))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "ITALY"))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "LATVIA"))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "LITHUANIA"))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "LUXEMBOURG"))
        self.comboBox_4.setItemText(20, _translate("MainWindow", "MONACO"))
        self.comboBox_4.setItemText(21, _translate("MainWindow", "NETHERLANDS"))
        self.comboBox_4.setItemText(22, _translate("MainWindow", "NORWAY"))
        self.comboBox_4.setItemText(23, _translate("MainWindow", "POLAND"))
        self.comboBox_4.setItemText(24, _translate("MainWindow", "PORTUGAL"))
        self.comboBox_4.setItemText(25, _translate("MainWindow", "ROMANIA"))
        self.comboBox_4.setItemText(26, _translate("MainWindow", "RUSSIA"))
        self.comboBox_4.setItemText(27, _translate("MainWindow", "SLOVAKIA"))
        self.comboBox_4.setItemText(28, _translate("MainWindow", "SLOVENIA"))
        self.comboBox_4.setItemText(29, _translate("MainWindow", "SPAIN"))
        self.comboBox_4.setItemText(30, _translate("MainWindow", "SWITZERLAND"))
        self.comboBox_4.setItemText(31, _translate("MainWindow", "TURKEY"))
        self.label_9.setText(_translate("MainWindow", "Card Number:"))
        self.pushButton_2.setText(_translate("MainWindow", "SAVE INFO"))
        self.label_12.setText(_translate("MainWindow", "CVV:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "VISA"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "AMERICAN EXPRESS"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "MASTERCARD"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "SOLO"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "PAYPAL"))
        self.label_14.setText(_translate("MainWindow", "SETTINGS"))
        self.label_17.setText(_translate("MainWindow", "PROXY HTTP/HTTPS:"))
        self.label_18.setText(_translate("MainWindow", "SIZE:"))
        self.radioButton_8.setText(_translate("MainWindow", "MEDIUM"))
        self.radioButton_9.setText(_translate("MainWindow", "LARGE"))
        self.radioButton_10.setText(_translate("MainWindow", "XLARGE"))
        self.pushButton_6.setText(_translate("MainWindow", "SAVE SET"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_3.setText(_translate("MainWindow", "BACK"))
        self.pushButton_5.setText(_translate("MainWindow", "UPDATE ITEMS"))
        self.radioButton.setText(_translate("MainWindow", "Image On"))
        self.radioButton_2.setText(_translate("MainWindow", "Image Off"))
        self.pushButton_4.setText(_translate("MainWindow", "DELETE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Order"))


class Ui_SuccessWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(200, 150)
        MainWindow.setMinimumSize(QtCore.QSize(200, 150))
        MainWindow.setMaximumSize(QtCore.QSize(200, 150))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 50, 161, 17))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 100, 89, 25))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Data saved successfully"))
        self.pushButton.setText(_translate("MainWindow", "OK"))


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 165)
        Dialog.setMinimumSize(QtCore.QSize(250, 165))
        Dialog.setMaximumSize(QtCore.QSize(250, 165))
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 120, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 111, 20))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.label.setText(_translate("Dialog", "Not all fields are filled in"))
        self.label_2.setText(_translate("Dialog", "please try again"))


class Ui_ProxyError(object):
    def setupUi(self, ProxyError):
        ProxyError.setObjectName("ProxyError")
        ProxyError.resize(240, 120)
        ProxyError.setMinimumSize(QtCore.QSize(240, 120))
        ProxyError.setMaximumSize(QtCore.QSize(240, 120))
        self.label = QtWidgets.QLabel(ProxyError)
        self.label.setGeometry(QtCore.QRect(20, 30, 201, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ProxyError)
        self.label_2.setGeometry(QtCore.QRect(80, 60, 67, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(ProxyError)
        self.pushButton.setGeometry(QtCore.QRect(70, 90, 89, 25))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ProxyError)
        QtCore.QMetaObject.connectSlotsByName(ProxyError)

    def retranslateUi(self, ProxyError):
        _translate = QtCore.QCoreApplication.translate
        ProxyError.setWindowTitle(_translate("ProxyError", "Proxy Error"))
        self.label.setText(_translate("ProxyError", "Any problems with the proxy"))
        self.label_2.setText(_translate("ProxyError", "Try other"))
        self.pushButton.setText(_translate("ProxyError", "OK"))